name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.lunary.ai
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: docker/private
          file: docker/private/Dockerfile
          push: true
          tags: registry.lunary.ai/dummy-image:latest

      - name: Clean up post-build
        if: always()
        run: git submodule deinit -f --all || echo "Submodule deinit failed"
