name: E2E Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Start the development server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_APP_URL: http://localhost:8080
          LUNARY_PUBLIC_KEY: 259d2d94-9446-478a-ae04-484de705b522

        run: |
          npm run dev &
          npx wait-on http://localhost:3333

      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
